### PR TITLE
Fix Conditional Question Selection + other fixes

### PR DESCRIPTION
**Pull request by cayb0rg**
There's an issue with how the player side is choosing "the question with the most required items and visits" since it's trying to get the most recent item as well. I'd like to propose changing the conditional question logic to select the question with the most recently acquired items/visits, and _then_ the question with most items/visits. This PR also updates the creator dialog to reflect this, hopefully clearly (if not, let me know how I can better word it). 

**For example**: There are three conditional questions. The first requires 3 visits. The second requires 1 visit and 1 item (Coffee). The third requires 2 visits, and 1 item (Book). _Originally_, if the player met the requirements for the third question before getting Coffee, the second question would never be shown because the third question has more visits overall. This would require the player to get Coffee before Book, but in some instances it may be hard to predict the order in which player acquires items. The same would happen for the first conditional question; if the player gets the third question before they have 3 visits, the first would never be shown. 

This PR changes it so that the player will be able to still see the second and first conditional questions once they meet the requirements, even if they have met the requirements for the third.

If this is still unclear or doesn't make as much sense as before, let me know what needs adjusting!

**Additional bug-fixes**
* Fixes display of ranges for missing required items in feedback dialog
* Fixes auto scroll in advanced question editor

### CODE REVIEW

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
There's still some weirdness going on here. I tested with the following:

Two items, A and B. I can receive either item and then progress to a node that has the following question states:
- No items
- 1x of item A
- 1x of item B
- 2x of item B

If I acquire items in the following order: A -> A -> B

I get the following conditional questions displayed:

1x of item A (correct), 2x of item A (correct), 1x of item A (huh?)

Other variations seem to check out - so perhaps this is just an edge case?

Something else I'm thinking about - the check for which conditional question to display should be the same between the player and score screen, but the code to make that check is effectively duplicated, and must be kept in lockstep. I'm wondering if it's worth putting it in a service instead, so the player and score screen can rely on the same function.

**Comment by cayb0rg** [comment]
Thank you for testing it out! I realized there was a major flaw in how I was tracking previously shown questions as well as the last shown question for each node, which may have been causing the issue you were having. 

I pushed a fix for that and moved the conditional question functions to their own service. I'm going to continue working on making them compatible with the score screen.

**Comment by cayb0rg** [comment]
~~Just noticed my changes are causing the narrative nodes to not render properly in the scorescreen. Working on a fix.~~ Fixed.

~~Also working on bugs in player from creating the service.~~ Fixed.

**Review by clpetersonucf — APPROVED** [review]
hell yea 😎

**Pull request merged**
